// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cloud_logic': 'enable',
    'aws_cloud_logic_custom': [{"id":"f5ci3muut6","name":"sampleCloudApi","description":"","endpoint":"https://f5ci3muut6.execute-api.us-west-2.amazonaws.com/Development","region":"us-west-2","paths":["/items","/items/123"]}],
    'aws_cognito_identity_pool_id': 'us-west-2:5621c5ed-e318-45d5-9525-e8ec18b1e340',
    'aws_cognito_region': 'us-west-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'amplifyionic-hosting-mobilehub-1879784717',
    'aws_content_delivery_bucket_region': 'us-west-2',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd20py8kower92l.cloudfront.net',
    'aws_dynamodb': 'enable',
    'aws_dynamodb_all_tables_region': 'us-west-2',
    'aws_dynamodb_table_schemas': [{"tableName":"amplifyionic-mobilehub-1879784717-AWSMobileTable","attributes":[{"name":"teamId","type":"S"},{"name":"personId","type":"S"},{"name":"email","type":"S"},{"name":"personName","type":"S"},{"name":"phone","type":"S"}],"indexes":[{"indexName":"personName-index","hashKey":"teamId","rangeKey":"personName"}],"region":"us-west-2","hashKey":"teamId","rangeKey":"personId"}],
    'aws_mobile_analytics_app_id': 'fa2c53818071480b8612417117a161a9',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '7c5ff222-897c-4940-82db-4cd2a36c59c1',
    'aws_project_name': 'amplify-ionic-4',
    'aws_project_region': 'us-west-2',
    'aws_resource_bucket_name': 'amplifyionic-deployments-mobilehub-1879784717',
    'aws_resource_name_prefix': 'amplifyionic-mobilehub-1879784717',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-west-2_C1r4Qqxxg',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '72so7i5mqsvf6r67qm8vof4k5',
}

export default awsmobile;
