// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-west-2:edb27625-79a4-4017-a5cc-99366bfcfe6e',
    'aws_cognito_region': 'us-west-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'tutorial-hosting-mobilehub-434947702',
    'aws_content_delivery_bucket_region': 'us-west-2',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd17hsvktu3ht9e.cloudfront.net',
    'aws_mobile_analytics_app_id': '80103222d4514bba949cc4ccf6ee096b',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '3dd87a0e-ab3d-44d2-ae94-918242e42fac',
    'aws_project_name': 'tutorial',
    'aws_project_region': 'us-west-2',
    'aws_resource_name_prefix': 'tutorial-mobilehub-434947702',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-west-2_VOSSwMQpq',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '1o8g4fcr0dg1thvubh7odivb38',
}

export default awsmobile;
